/* Extracted from configure.ac */

#define LIBMODBUS_VERSION_MAJOR 3
#define LIBMODBUS_VERSION_MINOR 1
#define LIBMODBUS_VERSION_MICRO 6
#define LIBMODBUS_VERSION_STRING "3.1.6"
#define LIBMODBUS_VERSION_HEX \
    (LIBMODBUS_VERSION_MAJOR << 16) | \
    (LIBMODBUS_VERSION_MINOR << 8) | \
    (LIBMODBUS_VERSION_MICRO)

#define LIBMODBUS_VERSION_CHECK(x, y, z) \
    (LIBMODBUS_VERSION_MAJOR >= x) && \
    (LIBMODBUS_VERSION_MINOR >= y) && \
    (LIBMODBUS_VERSION_MICRO >= z)

